from typing import Callable, Concatenate, overload

class aliasclassmethod[T, **P, R_co](classmethod[T, P, R_co]): ...

#     @property
#     def __func__(self) -> Callable[Concatenate[type[T], P], R_co]: ...
#     @property
#     def __isabstractmethod__(self) -> bool: ...
#     def __init__(self, f: Callable[Concatenate[type[T], P], R_co], /) -> None: ...
#     @overload
#     def __get__(
#         self, instance: T, owner: type[T] | None = None, /
#     ) -> Callable[P, R_co]: ...
#     @overload
#     def __get__(self, instance: None, owner: type[T], /) -> Callable[P, R_co]: ...

#     __name__: str
#     __qualname__: str

#     @property
#     def __wrapped__(self) -> Callable[Concatenate[type[T], P], R_co]: ...
# aliasclassmethod = classmethod
